### ISSUE TITLE
Support -moz-, -ms, -o prefix

### ISSUE THREAD

**Issue by yisibl** [hallvors/postcss-gradientfixer#3]
I hope the plugin's function is complete.

**Comment by gucong3000** [comment]
@yisibl 
In addition to `-webkit-gradient`, other properties have been fully supported.
除了`-webkit-gradient`,其他属性已经完全支持。

**Comment by yisibl** [comment]
@gucong3000 Awesome!

**Comment by gucong3000** [comment]
@yisibl 这个需求可以关掉了
