### ISSUE TITLE
eachDecl is deprecated

### ISSUE THREAD

**Issue by reitermarkus** [hallvors/postcss-gradientfixer#6]
According to the warning generated:

```
Container#eachDecl is deprecated. Use Container#walkDecls instead.
```

**Comment by reitermarkus** [comment]
https://github.com/hallvors/postcss-gradientfixer/issues/5

**Comment by hallvors** [comment]
https://github.com/hallvors/postcss-gradientfixer/commit/bb531e68b5c06a8c915799943f38f6bcbd0a1402
