### ISSUE TITLE
expression aways true #8

### ISSUE THREAD

**Issue by gucong3000** [hallvors/postcss-gradientfixer#9]
https://github.com/hallvors/postcss-gradientfixer/blob/master/index.js#L9
It's aways true.

**Comment by hallvors** [comment]
Right, this is a poor port from a different API.
walkDecls docs:
https://github.com/postcss/postcss/blob/master/docs/api.md#containerwalkdeclspropfilter-callback
Note that the "filter" argument can be a regexp. We should move the prefixAgnostic check to outside the walkDecls call and use it to pass either a regexp `-\w+-` plus _name_ or the simple string name as a filter.

Same applies to
https://github.com/hallvors/postcss-flexboxfixer/issues/8
